var status = [];
status.push("我知道我没那么幸运，只是觉得还不错，就这样");
status.push("为了这个拼了，竟然都关注了");
status.push("话说抽奖这东西是不是抽到就很nice了，有的挑么？");
status.push("喂喂喂 我我我 ");
status.push("萌萌哒，抽我吧，抽我吧，抽我吧 ");
status.push("棒棒棒！！");
status.push("抽中我吧");
status.push("博主真是良心大大的发放好福利～");
status.push("我转的都刷屏掉粉了，求抽我 我转的都刷屏掉粉了，求抽我");
status.push("这个可以有 来一个呗～");
status.push("萌萌萌！");
status.push("so cute~");
status.push("铁了心当分母");
status.push("不如干三天兼职上淘宝买一个");
status.push("现在已经是多少分之一的概率了");
status.push("嗷嗷嗷");
status.push("抽我啊，抽我啊，");
status.push("我想要！！！看到我！！");
status.push("我要我要啊啊啊！！");
status.push("这么多人转发。肯定抽不到我！不开森");
status.push("其实对这部东西本身不是很感兴趣~");
status.push("拉低中奖率。。。");
status.push("眼馋！");
status.push("看我这！快看我这！！");
status.push("抽不中请告诉我购买地址");
status.push("赞到我怀里 [加油啊][加油啊][加油啊]");
status.push("随手转发增大分母。。");
status.push("萌萌哒抽我抽我抽我");
status.push("我的小心肝！！！");
status.push("咦……既然这么可爱我也来转一发！ ");
status.push("喔喔喔 送我送我 么么哒");
status.push("来来来！快到怀里来 [加油啊]");
status.push("我的最爱啊，一定要拿到 ");
status.push("感觉不会种诶……");
status.push("反正抽不到，恳请博主指条明路让大家有的买啊");
status.push("让我在有生之年被抽中一次奖吧否则都不相信爱情了");
status.push("我要是被抽到了以后该倒多大得霉……");
status.push("转发是有必要的，万一呢 ，无聊的时候");
status.push("宝剑赠英雄，抽得有缘人，就是我！ [加油啊]");
status.push("原来是抽奖，必须要中我啊");
status.push("考验人品的时候到了。。");
status.push("转发一定要有的，万一中了呢");
status.push("既然大家拉低中奖率。。。那我");
status.push("我读书少 你别骗我");
status.push("噢噢!终于出来了，一直在等这个!求人品爆发啊，让我这个学生穷比省一点钱吧");
status.push("感觉不转都对不起自己啊，做个分母也是不错滴");
status.push("万水千山总是情,快点抽我行不行");
status.push("做梦就要做的美一点");
status.push("福利都不错哦，支持一下吧");
status.push("以后遇到这个抽奖我得转，抽不中也能攒人品了");
status.push("么么哒万一万一万一万一！！！！！");
status.push("奖品我很喜欢，感谢小编为粉丝们争取这么好的活动，期待可以收获一份惊喜！祝小编工作顺心，微博红红红火火 粉丝多多 活动圆满能成功。领盒饭去咯");
status.push("祝好运求好运 ");
status.push("好运来呀么好运来");
status.push("愉快的作为丐帮转 [江南style][江南style]");
status.push("梦想还是要有的，万一就实现了呢");
status.push("心情不好必须得转！！！转！");
status.push("加油加油，抽到我！！");
status.push("狠狠的抽我吧");
status.push("我竟然已经穷到这个地步了[doge]");
status.push("额。。。赤裸裸的抽奖。。。。");
status.push("最近比较穷 抽我 而且我们还是本行。");
status.push("[偷乐][偷乐]");
status.push(" 来来来让脑动成为人品的强有力支撑");
status.push("单纯的转着");
status.push("从来不信狗屎运这回事~~【哎呀，手滑~】 [吃惊]");
status.push("就这样安静地做个美女子，等你来抽我 ");
status.push("愉悦的转发");
status.push("我不为了中奖，就为了拉低中奖率。");
status.push("一切还来得及吗 [泪流满面]");
status.push("没钱买冰棍了，希望能抽中。 ");
status.push("我知道是不会抽中我的");
status.push("让我中一次！中奖概率会不会比彩票低→_→");
status.push("这难道就是传说中的随手转发正能量。");
status.push("抽我吧抽我吧啪啪啪！");
status.push("虽说每次都拉低中奖率…可今天是我的生日呢 就让我中一次奖不可以吗");
status.push("我！");
status.push("我才不信");
status.push("诶，刚看到[耶]，好像还赶得上。。。噗哈哈");
status.push("人生唯一愿望就是中奖");
status.push("抽中我的话，我决定去买彩票");
status.push("两边脸准备好了，请抽我吧");
status.push("哎吗 求中奖");
status.push("我就转转，反正也抽不中");
status.push("这种事怎么少的了我！");
status.push("来吧，我做好中奖的准备了！还没转的赶紧吧");
status.push("感觉会中的人随意转发都会中 像我们这种不会中的人怎么转发也没用");
status.push("快到我碗里来");
status.push("我也试试");
status.push("转发微博");
status.push("介个是真的？！");
status.push("来来。。我是一颗菠菜。。菜菜菜。。");
status.push("互联网时代有一技之长是多么的重要~");
status.push("以为考完试可以小放松一下~结果接了个可恶的电话，现在得去准备明天要交到税务局的材料了早知道从考试到现在一直关机好了");
status.push("给力活动必须支持");
status.push("抽奖是一定要参与的，万一抽中了呢？ ");
status.push("么么哒抽我吧看过来呀");
status.push("来来来 maybe");
status.push("rprprprprprp");
status.push("应该比彩票几率高？");
status.push("啊啊啊啊啊啊啊.~");
status.push("放着我来！！！！");
status.push("第一次。试试");
status.push("怎么能不转发拉低中奖率呢");
status.push("拉低中奖率，顺便赌人生[doge]");
status.push("我转 拉低中奖路 什么鬼");
status.push("求中，穷疯了。");
status.push("这一定是要参与的，万一中了呢？？ ");
status.push("选我选我选我 啊啊啊啊啊 ");
status.push("世道炎凉 我沦落至此");
status.push("我就喜欢拉低中奖率");
status.push("如果我中了，我心情更愉悦地说 [偷乐]");
status.push("还是要转一下的 ，万一中了呢 [得意地笑] [得意地笑] [得意地笑]");
status.push("转一下又不会怀孕~");
status.push("刚来就看到了这样的福利 [哈哈][哈哈]");
status.push("我是诚实的孩子，我就是要奖品");
status.push("默默转发");
status.push("。。。。。。。。求中奖 [加油啊]");
status.push("不转白不转");
status.push("债主满天下，微博小秘书自动转发。");
status.push("又是拼人品的时刻了");
status.push("大家会不会因为我执着参与抽奖而取关，一定会");
status.push("抽我好了，come on ");


function resort(array) {
	for(var i=0; i<array.length; i++) {
		var ti = Math.floor(Math.random() * array.length);
		var o = array[ti];
		array[ti] = array[i];
		array[i] = o;
	}
}

resort(status);
